APP_BINARY=./mkt_dev
TEMPLATES_DIR="$HOME/.mkt-dev/templates"
GREEN='\033[0;32m'
RED='\033[0;31m'
BOLD='\033[1m'
RESET='\033[0m'

FAILED="${RED}${BOLD}FAILED${RESET}"
SUCCESS="${GREEN}${BOLD}SUCCESS${RESET}"