[package]
name = "bin_app"
version = "0.2.3"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
txml_processor = { path = "../txml_processor" }